name: build
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Print a message
        run: echo "Hello World!"

      - name: Build Rust dynamic library
        run: cargo run --verbose
        working-directory: ./Rust

      - name: Build Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
        
      - name: Store saigai
        uses: actions/upload-artifact@v4
        with:
          name: sagai-solver-windows-x64
          path: build/StandaloneWindows64