name: build
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello World!"